services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    hostname: code-server
    restart: unless-stopped
    ports:
      - "8443:8443"
      - "4200-4202:4200-4202"
      - "5173-5175:5173-5175"
      - "5100:5100"
    volumes:
      - ${UMBREL_ROOT}/home/Work:/config:rw
      - ${APP_DATA_DIR}/custom-cont-init.d:/custom-cont-init.d:ro
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "987" # Replace 999 with the output of `stat -c '%g' /var/run/docker.sock`
    env_file:
      - path: ${UMBREL_ROOT}/home/Work/.env
        required: false
      - path: ${APP_DATA_DIR}/.env
        required: false
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DEFAULT_WORKSPACE=/config/workspace
      - PWA_APPNAME=code-server
      - APT_PACKAGES=nodejs npm claude
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_SOCK_GID=987
