services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    hostname: n8n
    user: "0:0"
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ${APP_DATA_DIR}/data:/home/node/.n8n:rw
    environment:
      TZ: America/Sao_Paulo
      N8N_HOST: umbrel.taile9d9d9.ts.net
      N8N_PORT: 5678
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://umbrel.taile9d9d9.ts.net/
      N8N_SECURE_COOKIE: "false"
